# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/All/Software/ZZ-Hardware_Old/Sample_Code_Alghasi/Sample_project_QSPI_Upper256/Sample_project_QSPI_Upper256.srcs/sources_1/bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xci
# IP: The module: 'hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/All/Software/ZZ-Hardware_Old/Sample_Code_Alghasi/Sample_project_QSPI_Upper256/Sample_project_QSPI_Upper256.srcs/sources_1/bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/All/Software/ZZ-Hardware_Old/Sample_Code_Alghasi/Sample_project_QSPI_Upper256/Sample_project_QSPI_Upper256.srcs/sources_1/bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xci
# IP: The module: 'hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/All/Software/ZZ-Hardware_Old/Sample_Code_Alghasi/Sample_project_QSPI_Upper256/Sample_project_QSPI_Upper256.srcs/sources_1/bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
